### ISSUE TITLE
TimeZone arg get capsed in parse_date call

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog-plugin-pipeline-processor#100]
### Problem description
![image](https://cloud.githubusercontent.com/assets/17475270/18309402/fc82d696-7501-11e6-85cf-542dc4fc6878.png)

It was OK before update.

### Environment
* Graylog Version: 2.1.0 (62db7e0)
* Pipeline Processor plugin version:  1.1.0

**Comment by hc4** [comment]
Actualy I can't configure correct timezone now.
Where can I get list of all timezones?

UTC+3 not working
GMT+3 not working
Etc/GMT+3 not working

I'm lost :)

**Comment by hc4** [comment]
Found solution.
Set timezone to "+03"

**Comment by kroepke** [comment]
The issue is that we chose to uppercase the timezone because the parser requires exact matches for "UTC", e.g.
I guess we need a lookup table for the zones :/

**Comment by joschi** [comment]
@kroepke I don't get the reason for using the upper case version of the timezone. Could you please elaborate on that?

**Comment by kroepke** [comment]
@joschi people were trying `utc` and expected that to work. That lead me to the mistake of simply uppercasing the timezone ID, but I forgot about the geographic names.
I've replaced it with a static lookup map now and added tests (see PR)
