### ISSUE TITLE
route_to_stream() fails with identically named streams

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog-plugin-pipeline-processor#101]
### Problem description

The `route_to_stream()` function fails if multiple streams with the same name exist.

Refs: https://groups.google.com/d/msg/graylog2/wlCKyqAk4GA/EPfN7AH5AQAJ
### Steps to reproduce the problem
1. Create two identically named streams in Graylog (e. g. "Test")
2. Create a pipeline rule using the `route_to_stream()` function and the stream name as parameter (e. g. `route_to_stream(name: "Test");`
3. See error while running that rule:

```
gl2_processing_error

For rule 'pipelinerule1': In call to function 'route_to_stream' at 8:4 an exception was thrown: Multiple entries with same key: string=57cfba54ad0b4b09fe3fde0f: "string" and string=57cfba51ad0b4b09fe3fde09: "string". To index multiple values under a key, use Multimaps.index.
```
## Expected behavior

The `route_to_stream()` function should route the message into all streams with the given name.
### Environment
- Graylog Version: 2.1.0
- Pipeline Processor plugin version: 1.1.0

**Comment by liukd** [comment]
I met a problem, the hope can help to solve it. I want to build a development environment but execute the following command, and I was not successful
* `git clone https://github.com/Graylog2/graylog2-server.git`
* `cd graylog2-server/graylog2-web-interface`
* `ln -s $YOURPLUGIN plugin/`
* `npm install && npm start`

**Comment by joschi** [comment]
@liukd Please don't hijack issues with completely unrelated problems.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
