### ISSUE TITLE
Pipeline doesn't drop message unless attached to Default stream

### ISSUE THREAD

**Issue by Alekc** [Graylog2/graylog-plugin-pipeline-processor#103]
Not sure if it's a bug or my misunderstanding of documentation. 

I have a pipeline with following rule in it

```
rule "drop cronjob"
when 
    has_field("application_name") && to_string($message.application_name) == "CRON"
then
    drop_message();
end
```

If I attach this pipeline to "**Syslog**" stream, messages are not dropped, and I still can see them in the stream. Only if I attach the pipeline to **Default** stream, messages begin to be dropped. 

Is it a normal behaviour?

**Comment by jalogisch** [comment]
Hej @Alekc 

this is not *normal* as this does not follow your rule. It sounds more like a support question, as it is working in the default stream. 

I do have something similar in my setup and that is working without a problem. What *stage* do you have set this pipeline? maybe something before move the message out or it is moved in this stream after the pipeline that deletes. 

Please repost your question if still present to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by Alekc** [comment]
Ok, thx. 

I will move it to public mail list.

**Comment by kroepke** [comment]
@Alekc Also check the processor order (System -> Configuration). If the stream matching is done after the pipelines, this effect can happen as well.

**Comment by Alekc** [comment]
@kroepke I've updated discussion on mailing list (https://groups.google.com/forum/#!topic/graylog2/lZvPQFBCKBc)
