### ISSUE TITLE
List of streams and pipelines names/connections are not ordered alphabetically.

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog-plugin-pipeline-processor#108]
### Problem description

The [connection form](https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/56b801b13751f3b1c87f6497abc507db0f662e22/src/web/pipeline-connections/ConnectionForm.jsx) (i.e. "Add new connection" and "Edit connections") does not list stream or pipeline names in alphabetical order.  Additionally, the [list of pipeline connections for a stream](https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/56b801b13751f3b1c87f6497abc507db0f662e22/src/web/pipeline-connections/Connection.jsx#L38) (on `/system/pipelines`) is not listed in alphabetical order.
### Steps to reproduce the problem
1. Log in to a 2.1.1 environment as an admin
2. Create several streams and pipelines (if needed)
3. Navigate to System --> Pipelines and click "Add new connection"
4. Note the streams and pipeline connections are not listed in alphabetical order
5. Connect some pipelines to a stream and click Save
6. Note the pipeline connections under the stream are not listed in alphabetical order
### Environment
- Graylog Version:  2.1.1+01d50e5
- Pipeline Processor plugin version:  1.1.1 (no change from 2.1.1 release)
- Elasticsearch Version:  2.2.0
- MongoDB Version:  2.6.12
- Operating System:  Red Hat Enterprise Linux Server release 6.8
- Browser version:  Firefox 49.0.1

**Comment by dennisoelkers** [comment]
Thanks for submitting this issue and your dedication to details. We will work this in in one of the next versions.

**Comment by kroepke** [comment]
During refactoring in 2.2 this issue has already been taken care, the streams are now listed in alphabetical order.
