### ISSUE TITLE
Import and export pipelines, connections, rules, etc.

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog-plugin-pipeline-processor#109]
### Problem description

It might be useful to have the ability to import and export pipeline artifact (connections, stages, rules, etc.).  Perhaps this would be similar to the example in the documentation's [Pipeline structure](http://docs.graylog.org/en/2.1/pages/pipelines/pipelines.html#pipeline-structure) section.
### Environment
- Graylog Version:  2.1.1+01d50e5
- Pipeline Processor plugin version:  1.1.1 (no change from 2.1.1)

**Comment by kroepke** [comment]
Internally pipelines are already represented as source code, so this makes a lot of sense to be able to export them.
I'm not sure we can fold it into the content pack mechanism, as that isn't pluggable as of now.

**Comment by liberomic** [comment]
Hi all,

do you have news for this request? 

Regards
Liberomic

**Comment by joschi** [comment]
@liberomic No. Any news would be visible in this issue.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
