### ISSUE TITLE
remove_from_stream function missing

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog-plugin-pipeline-processor#117]
It should be possible to "unroute" a message from a stream.

The function should eventually call `Message#removeStream` and have the same semantics as `route_to_stream`.

**Comment by jalogisch** [comment]
this should be made possible to have in the upcoming 2.2 release the option to route messages to a different stream and remove the default stream.

**Comment by SonofLiberty90** [comment]
Any updates on this feature request? We're constantly getting duplicated events due to this.

**Comment by kroepke** [comment]
@SonofLiberty90 Sorry, this fell through the cracks a bit.

We'll try and get this into 2.4 and 3.0. 2.4 is going into beta in the next few days unless something unexpected happens.

Thanks for the ping :)
