### ISSUE TITLE
drop_message() not working

### ISSUE THREAD

**Issue by dmitrime** [Graylog2/graylog-plugin-pipeline-processor#128]
### Problem description

I installed graylog from AWS AMI. I want to drop the annoying messages coming from the "nginx" source which is the nginx of the graylog machine itself. I tried everything, from trying to delete it from the config to writing drop rules. But it just keeps on spamming the index with useless messages. The only thing that works is disabling the "appliance-gelf-udp" input, but then messages from my app don't come in either. I had no luck with rules and it's puzzling to me that there are no example of such a simple "drop-everything" rule.

The following does not work when I create the pipeline for the "nginx requests stream" connection:

```
rule "drop nginx"
when
  true
then
  drop_message();
end
```

### Steps to reproduce the problem

1. Install Graylog from AWS AMI.
2. Create connection for "nginx requests stream".
3. Create a pipeline under the connection.
4. Add the above rule
5. source:nginx spam is still coming...

### Environment

* Graylog-2.1.1-1installed from the AMI ami-d3f022b3

**Comment by joschi** [comment]
@dmitrime You can simply run `sudo graylog-ctl disable-internal-logging` (see http://docs.graylog.org/en/2.1/pages/configuration/graylog_ctl.html#configuration-commands).

**Comment by dmitrime** [comment]
@joschi I tried that, unfortunately it's still keeps on sending messages.

```
sudo graylog-ctl disable-internal-logging
sudo graylog-ctl restart
```

**Comment by mariussturm** [comment]
@dmitrime I think a reboot is needed afterwards so that Runit can be started with the right options. No idea why this information vanished from the documentation :/

**Comment by dmitrime** [comment]
Reboot solved it, thank you very much!

@joschi @mariussturm I really appreciate the fast response from you!
