### ISSUE TITLE
Fix stage cache metrics reporting

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog-plugin-pipeline-processor#146]
### Problem description
current you will not get any metrics from the plugin

![graylog_pipe_line_metrics](https://cloud.githubusercontent.com/assets/404238/21143495/48563ba8-c147-11e6-818b-399e40c708cc.png)

### Environment

* Graylog Version:Graylog 2.2.0-beta.2+7cda131 OVA
* Pipeline Processor plugin version: 2.2.0-beta.2

**Comment by kroepke** [comment]
I think it is because the gauges are lambdas which for some reason breaks the metrics library.
There was another place where this happened (KafkaJournal?).
Should easily be fixable by using anon-subclasses.

Extra credit: figure out why this happens.
