### ISSUE TITLE
field names containing '-' cause errors

### ISSUE THREAD

**Issue by jcspino** [Graylog2/graylog-plugin-pipeline-processor#158]
### Problem description
Whenever I try to perform the to_string action on a field that contains a dash (-) in the name I get an error writing the rule. I have tried to escape the dash but I have not been able to make it work yet. It works fine if I use the $message.source field. 

Also, I realize that the creation of the y variable is incorrect but I need to get the first error resolved to figure out the proper syntax for creating the new string. The goal is to take the geo-ip which comes in as "23.4334, -12.3434" and change it to "[23.4334, -12.3434]" so that i can map it in Kibana. 

### Steps to reproduce the problem

1. Create pipeline in GL-2.1.2 
2. Create rule below. 

rule "Kibana Fields"
  when
          has_field("ip-c_geolocation")
  then
          let x = to_string($message.ip-c_geolocation);
         let y ="[" && x && "]";
         set_field("ip-geo", y);
 end

This error will appear on the "let x =" line. 
![image](https://cloud.githubusercontent.com/assets/19912595/22713289/d5b091f8-ed55-11e6-9495-8b9f0ef71ef5.png)

any help is appreciated. 

### Environment

* Graylog Version: 2.1.2
* Pipeline Processor plugin version: 1.1.2
* Elasticsearch Version: 2.4.2
* MongoDB Version: 3.2.6
* Operating System: CentOS7
* Browser version: Chrome 55.0 64bit

thanks,
Jonathan

**Comment by joschi** [comment]
@jcspino The `-` character has a special meaning (subtraction) in the language used for the pipeline rules.

You have to use another notation to access these fields (see https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/1.1.3/src/test/resources/org/graylog/plugins/pipelineprocessor/parser/messageRefQuotedField.txt):
```
$message.`ip-c_geolocation`
```

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
