### ISSUE TITLE
Pipeline rules unable to use fields created by Extractor

### ISSUE THREAD

**Issue by Velyks** [Graylog2/graylog-plugin-pipeline-processor#163]
### Problem description
I'm trying to make a pipeline rule that uses a field created by a Grok extractor from the main message, but this field is not visible to the pipeline rules at all.

### Steps to reproduce the problem

1. Add a Grok extractor to the message field of a message, use it to create one new field.
2. Create a pipeline on the stream that message ends up in
3. Add a rule that uses the previously created field in the "when" or "then" sections of the rule.

### Environment

* Graylog Version: v2.2.2+691b4b7
* Pipeline Processor plugin version: Which ever one ships with the above.
* Elasticsearch Version: 2.4.4
* MongoDB Version: 2.6.10
* Operating System: Ubuntu 16.04
* Browser version: Firefox 52.0

**Comment by joschi** [comment]
@Velyks Check the order of message processors on the System / Configurations page. The Message Pipeline Processor has to run *after* the (old) Message Filters if you want to access fields created by extractors.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by Velyks** [comment]
That solved it, thanks. Yes this looks to be a user issue.

**Comment by sathishdsgithub** [comment]
@Velyks

I'm trying to combine two grok felds to a single field.

Example : Currently my grok extractors has field src_ip and dst_ip .

Now I want to use the pipeline to combine both the field  src_ip and dst_ip to a single field with name "src_dst_ip".

How do I achieve this with pipeline rules ? , Please post me the example.output .Thanks

**Comment by joschi** [comment]
@sathishdsgithub We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
