### ISSUE TITLE
Graylog Pipeline Processor Rule issues

### ISSUE THREAD

**Issue by ion-storm** [Graylog2/graylog-plugin-pipeline-processor#166]
I am having an issue where the first has_field option is not including has_field("sysmon_dns_lookup_ip") in the following pipeline filters after it using ||
Doing this:
```
    // Network Events
	has_field("sysmon_dns_lookup_ip") && is_not_null($message.sysmon_event_id) && $message.sysmon_event_id == "3" &&
	has_field("sysmon_dns_lookup_ip") && contains(to_string($message.sysmon_data_process), "at.exe", true) ||
	has_field("sysmon_dns_lookup_ip") && contains(to_string($message.sysmon_data_process), "certutil.exe", true) ||
	has_field("sysmon_dns_lookup_ip") && contains(to_string($message.sysmon_data_process), "cmd.exe", true) ||
	has_field("sysmon_dns_lookup_ip") && contains(to_string($message.sysmon_data_process), "cscript.exe", true) ||
	has_field("sysmon_dns_lookup_ip") && contains(to_string($message.sysmon_data_process), "wscript.exe", true) ||
	has_field("sysmon_dns_lookup_ip") && contains(to_string($message.sysmon_data_process), "rundll32.exe", true) ||
```
Works as expected, but doing just && then contains || contains || does not always include the first has_field.  

If i'm doing something wrong please tell me a better way.

Pipeline:
https://github.com/ion-storm/Graylog_Sysmon/blob/master/Pipelines/network%20threat%20indicator%20pipeline%20rule

**Comment by joschi** [comment]
@ion-storm Try being explicit about the evaluation order by putting braces (`(`, `)`)  around the expressions, for example:

```
(has_field("sysmon_dns_lookup_ip") && is_not_null($message.sysmon_event_id) && $message.sysmon_event_id == "3") &&
(has_field("sysmon_dns_lookup_ip") && contains(to_string($message.sysmon_data_process), "at.exe", true))
```

**Comment by ion-storm** [comment]
thanks will try that and report back

**Comment by ion-storm** [comment]
thanks, that seemed to work quite well, do you know if there is a rule that I can use to parse the end part of a string?  I am trying to identify ransomware files like so:
https://github.com/ion-storm/Graylog_Sysmon/blob/master/Pipelines/ransomware%20pipeline
`	contains(to_string($message.sysmon_data_file_created), ".crypto", true) ||
`
ideally, i'd like to be able to do: line end with .crypto because it will flag libraries like microsoft.cryptography .dll since .crypto is in the string.  Trying to find a clever way around this.

**Comment by ion-storm** [comment]
got it: 
```
rule "add file field"
when
  has_field("sysmon_data_file_created")
then
    let m = regex("([^/\\\\]+$)", to_string($message.sysmon_data_file_created));
    set_field("file_created", m["0"]);
end
```
