### ISSUE TITLE
Graylog - strange characters in the message field

### ISSUE THREAD

**Issue by WoB1953** [Graylog2/graylog-plugin-pipeline-processor#187]
Hello,

my name is Wolfgang and I am new at GitHub.

I am installing a new Debian 8 server.
As I am tired to struggle with the different big logfiles I first installed graylog to make my life more easy.

But now I have the problem, that the messages displayed in graylog are not readable.

They look like:
message: 
c�'��U+��l(B`�rH�
�2��M�K�!SnZݗ����r+�u��.n>��v��Aa}���a\��'�'���S]�M���RY7}Yw�l~4�j��7U��{_KU�����oE�}�x,�w��?~-"v'�U��sv�X��k� v����_�)�4-i�ɇ�͡zn��ce����¼0������/���1A=����t ���<�S��$�h��l]£�mv�L�

The origin messages in the logfiles are plain text and readable, all other text on the site too.

I could not figure out where and why they are converted to another format.
Neither where I can change this.

I searched Google but I did not find any related information.

My installation:
* Graylog Version: **2.2.3+7adc951, codename Stiegl**
* Pipeline Processor plugin version: 	**2.2.3**
* Elasticsearch Version:  **2.4.5**
* MongoDB version: **v2.4.10**
* Operating System: **Debian 8.8**
* Browser version: **Slimjet Version 11.0.2.0 (basierend auf Chromium 51.0.2704.84)** and
                              **Firefox 53.0.3 (32-Bit)**

I hope someone can help me.

Have a nice weekend
Wolfgang

**Comment by jalogisch** [comment]
Hej @WoB1953 

thank you for submitting this, but we are using GitHub issues for tracking bugs in Graylog itself, this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
