### ISSUE TITLE
Locale in parse_date()

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog-plugin-pipeline-processor#202]
In 2.3.0 **locale** arg was added to **parse_date()** function
![image](https://user-images.githubusercontent.com/17475270/28866859-eda3d606-777c-11e7-8567-080cefd68416.png)

But documentation was not updated.
Also meaning of **locale** in conjunction with **pattern** parameter is not clear

### Environment

* Graylog Version: 2.3.0
* Pipeline Processor plugin version: 2.3.0

**Comment by bernd** [comment]
Closed in #203
