### ISSUE TITLE
escape-style short classes in regex rule function

### ISSUE THREAD

**Issue by gclinch** [Graylog2/graylog-plugin-pipeline-processor#21]
Is it possible to pass in escape-style short classes (eg '\s'?) to the regex rule function?

This works:
`set_fields(regex("^(.*) (.*)$", to_string($message.message), ["test1", "test2"]));`

as does this:
`set_fields(regex("^(.*)[ ](.*)$", to_string($message.message), ["test1", "test2"]));`

.. but this can't be saved in the editor ('Undeclared variable regex in line 7 pos 4', 'token recognition error at: '$"'' etc etc'):
`set_fields(regex("^(.*)\s(.*)$", to_string($message.message), ["test1", "test2"]));`

The rule can be saved if the slash is doubled up, but the regex doesn't seem to match anymore.

**Comment by kroepke** [comment]
The change from #31 fixes this issue as well, closing this, please track the other issue.
We'll most likely release an updated version today.

Thanks for your report!
