### ISSUE TITLE
Feature Request for Function concate()

### ISSUE THREAD

**Issue by xtruthx** [Graylog2/graylog-plugin-pipeline-processor#215]
The function concate acutally allows only two values. It should be possible at least to concate three strings so that you are able to produce for example something like this:
```
concate(to_string($message.userfield)," logged on at client ",to_string($message.clientfield));
```
Actually i am building to variables and concate them.

**Comment by joschi** [comment]
This basically duplicates #95.

Instead of providing concatenate functions with three, four, five, six, etc. parameters, we'd rather implement proper string interpolation.

**Comment by xtruthx** [comment]
ok accepted. sounds better. sorry for the noise

**Comment by joschi** [comment]
@xtruthx No worries! Thanks for your request!
