### ISSUE TITLE
Rules Editor: "Rule source" too small and can't be resized

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog-plugin-pipeline-processor#229]
The text field for the rule source in the rules editor (System / Pipelines / Manage rules / Edit) is too small for many "real world" rules and cannot be resized in its length.

This seriously limits the usefulness of the rules editor and forces users to use a proper text editor to write the rules and then copy & paste them in to the rule source field for syntax validation and saving.

If the text field was resizable (or even automatically resized with the amount of available space on the page), it would be more useful for actually editing pipeline rules.

**Small window, small text area**
![Small window, small text area](https://user-images.githubusercontent.com/43951/33549106-b524bfba-d8e9-11e7-9be3-711c083f35ab.png)
**Medium-sized window, small text area**
![Medium-sized window, small text area](https://user-images.githubusercontent.com/43951/33549108-b8cdd840-d8e9-11e7-9d89-d3b506784fcb.png)
**Large window, small text area**
![Large window, small text area](https://user-images.githubusercontent.com/43951/33549115-bb82959e-d8e9-11e7-80bf-72b54d8ad41d.png)

References:
* https://developer.mozilla.org/docs/Web/CSS/resize

**Comment by bernd** [comment]
Fixed in Graylog2/graylog2-server#4419
