### ISSUE TITLE
Feature Request: Ability to reorder pipeline rules within a stage

### ISSUE THREAD

**Issue by ghost** [Graylog2/graylog-plugin-pipeline-processor#248]
### Feature description
As graylog pipelines work in a first-match wins way, I think a good bit of functionality to implement would be the ability to reorder the rules within a given stage of a pipeline.
Drag-and-Drop style would be good, like we have in the Message Processors Configuration section of System / Configurations

### Current solution to functionality
Current solution to do this means deleting the rule and re-adding it. This can be rather annoying if you need the rule to be above others currently in the pipeline but after a new rule that you're wanting to add, depending on the scenario, you could end up having to remove all rules from the pipeline and re-adding them.

### Environment
* Graylog Version: 2.4.5+8e18e6a
* Pipeline Processor plugin version: 2.4.5
* Elasticsearch Version: 5.6.10
* MongoDB Version: 1:2.6.10-0ubuntu1
* Operating System: Ubuntu
* Browser version: Chrome 67.0.3396.99 (64-bit)

**Comment by joschi** [comment]
@Nihlander All rules in a given pipeline stage are being executed at the same time.

If you want ordering, you'll have to use stages for that.

Also see http://docs.graylog.org/en/2.4/pages/pipelines/pipelines.html

> Think of stages as groups of conditions and actions which need to run in order.
