### ISSUE TITLE
Provide .jar releases

### ISSUE THREAD

**Issue by tokred** [Graylog2/graylog-plugin-pipeline-processor#33]
Bear with me, but am I wrong if I say that there are no .jar releases available and the README's Installation section is wrong? Would it be possible to provide compiled .jar's?

**Comment by edmundoa** [comment]
The thing is, for now you don't really need to install it by hand: the plugin is included in the Graylog 2.0 tarball and packages by default, and it is not compatible with previous versions.

I will update the readme and, if you really need to download it, I'd recommend downloading the latest Graylog tarball from the [downloads page](https://www.graylog.org/download/) and getting the jar file that is inside the `plugin` folder.
