### ISSUE TITLE
RegexMatcher: Pattern always require full string match

### ISSUE THREAD

**Issue by tokred** [Graylog2/graylog-plugin-pipeline-processor#35]
### Problem description
Due to wrongly non-matching regex patterns, I noticed an abnormal and inefficient behavior of the current implementation of regex() function: The pattern always has to match on the full string value to return true instead of matching on substrings (next match).

Example: `regex(pattern: "^foo", value: "foobar")` is a non-match 
while `regex(pattern: "^foo.*", value: "foobar")` is a match.

This contradicts standard regex implementations, leads to unnecessary regex state machine steps (especially for leading greedy `.*`!) and therefore to inefficient message processing!

**Reason:** RegexMatch.evaluate() uses java.util.regex.Matcher.matches() instead of next-match find(). Also check out this discussion on the [differences](http://stackoverflow.com/questions/4450045/difference-between-matches-and-find-in-java-regex).

### Steps to reproduce the problem

1. Create a pipeline rule with a regex when-condition.
2. Set a pattern which matches a substring of messages, see above. The condition will be false.
3. Modify the pattern to `.*<Pattern>.*`. The condition will be true.

### Environment

* Graylog Version: 2.0.2
* Pipeline Processor plugin version: 1.0.0-beta.4

**Comment by kroepke** [comment]
Good point, it was initially modeled after the extractor code which isn't exactly what we wanted here.

I'll fix this for 2.1
