### ISSUE TITLE
Provide a key=value function

### ISSUE THREAD

**Issue by tokred** [Graylog2/graylog-plugin-pipeline-processor#38]
In order to replace a key=value input extractor, I would be happy if you could provide an equivalent key=value rule function, e.g.
````
parse_kv( to_string($message.myfield) );
````

For cases where you do not control the naming of keys (or the keys are ambiguous/generic like "source", "destination", etc.), an optional prefix parameter would be helpful to make field names distinctive, e.g.
````
parse_kv( value: x, prefix: "myservice_" );
````

**Comment by jalogisch** [comment]
get inspiration from [logstash kv parser](https://www.elastic.co/guide/en/logstash/current/plugins-filters-kv.html) 

some of the advanced could be very handy (trim, trimkey, include_key)
