### ISSUE TITLE
Pipelines connected to streams do not run

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog-plugin-pipeline-processor#48]
### Problem description

Any pipeline I am trying to connect to a stream different than the "Default Stream" will never run. The simulator executes just fine.

When connecting the same pipeline to the "Default Stream", all stages are executed properly.

### Steps to reproduce the problem

1. Create a pipeline with stages and rules in it
2. Connect that pipeline to a stream
3. See that newly arriving messages in the stream are not being mutated
4. Connect the same pipeline to the "Default Stream" instead
4. See that messages are being properly mutated

### Environment

* Graylog Version: 2.1.0-alpha.3
* Pipeline Processor plugin version: 1.1.0-alpha.2 (built from current `master`)
* Elasticsearch Version: 2.3.1
* MongoDB Version: 3.0.0
* Operating System: OSX

**Comment by kroepke** [comment]
Is the message processor order correct?
It can easily happen that the pipeline processor is running before the stream matcher.

**Comment by lennartkoopmann** [comment]
That is correct. Can we add a very bold note about this on the pipeline connection page and the docs? I had no clue. :)

**Comment by mikkolehtisalo** [comment]
:+1:

**Comment by nwalke** [comment]
Having just installed graylog for the first time, the default ordering puts `Message Filter Chain` after `Pipeline Processor`.  Shouldn't those be switched by default?

**Comment by bernd** [comment]
@nwalke The desired order depends on what you want to run first. While it sounds reasonable to have the `Message Filter Chain` run first, we cannot change it now because that would be a backwards incompatible change and can break existing setups in subtle ways.
