### ISSUE TITLE
Grok extractor: Allow returning only named captures

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog-plugin-pipeline-processor#59]
as this is available in the server: https://github.com/Graylog2/graylog2-server/issues/1486

this should be ported to the pipelines

**Comment by tokred** [comment]
Actually, this request already exists for some time in a similar manner :(
https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/22

**Comment by kroepke** [comment]
@tokred the issue is that without treating every regex as a grok pattern we cannot solve #22 unless we switch the regex library
upstream java-grok now supports "named captures only" so in 2.1 we'll support that.
Switching the default regex library is a little too much for this release, sorry
