### ISSUE TITLE
Obsolete rule could be opened in EDIT mode

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog-plugin-pipeline-processor#60]
### Steps to reproduce the problem
1. Open Pipeline Rules in two browser tabs
2. Edit and save rule in first tab
3. Start edit same rule in second tab
4. Rule without changes, made on 2nd step will be opened
5. If you click Save - it will be saved (all changes from 2nd step will be lost).
### Environment
- Graylog Version: 2.1.0-beta1
- Pipeline Processor plugin version: 1.1.0-beta1

**Comment by kroepke** [comment]
This is a general behavior in all of a Graylog currently, we do not version objects right now.

It needs to be addressed in a more generic manner, thus I'm closing this request.
