### ISSUE TITLE
Add function to check if value is null

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog-plugin-pipeline-processor#62]
I want to check if regex group was matched.
```
let m = regex("(\\d+)");
set_field("value_found", !is_null(m["0"]));
```

Maybe also **is_not_null** could be added.
Or just add keyword **null** and possibility to use equality operators

**Comment by kroepke** [comment]
This works for me.
```
rule "regexMatch"
when
    regex(".*(cde\\.)(:(\\d+))?.*", "abcde.fg").matches == true
then
    let result = regex(".*(cd\\.e).*", "abcd.efg");
    set_field("group_1", result["0"]);
    set_field("has_group_1_matched", is_not_null(result["0"]));
    set_field("matched_regex", result.matches);
end
```

`is_null` and `is_not_null` should be available already. I only have a 2.1 dev version quickly available now, but I think this works today.

**Comment by hc4** [comment]
Hm, it works for me too :)
Funny - I just read docs and there was not is_null function, and I even didn't try to test it.

**Comment by kroepke** [comment]
The docs are lacking right now, that is true. I have it on my list to update them to include all currently shipped functions. (they are currently static, unfortunately).

I'll leave this one open for the docs part then.

Thanks!

**Comment by kroepke** [comment]
actually there's already a ticket for the docs #56 
closing this one
