### ISSUE TITLE
Release to maven repos

### ISSUE THREAD

**Issue by mikkolehtisalo** [Graylog2/graylog-plugin-pipeline-processor#67]
Pipeline-processor should be released in the maven repos, like usage-statistics has been. See [org.graylog.plugins](http://search.maven.org/#search%7Cga%7C1%7Corg.graylog.plugins)

This would make building dependencies for 3rd party plugins that implement new functions etc slightly more effortless. For now I just

`mvn install:install-file -Dfile=target/graylog-plugin-pipeline-processor-1.1.0-beta.2-SNAPSHOT.jar -DpomFile=pom.xml`

and then reference it, but it would be nicer if it was in repos.

**Comment by kroepke** [comment]
Good point, that was the intention all along, including publishing it on the marketplace, too.

**Comment by kroepke** [comment]
This is now done for 1.1.0 and 1.1.1.
In the future we will automatically deploy to central, leaving this open until we merge that branch.

**Comment by kroepke** [comment]
2.2 will automatically do that, for 3.0 we will likely merge the plugin into core as it stabilized and is generally useful.
