### ISSUE TITLE
in order to implement custom pipeline functions in separate plugins the pipeline-plugin needs to be declared with shared class loader

### ISSUE THREAD

**Issue by kaililleby** [Graylog2/graylog-plugin-pipeline-processor#81]
### Problem description
Adding new pipeline functions in separate plugins requires access to classes defined in the pipeline-plugin. With the release of graylog 2.1.x plugins by default do not share a global class loader (se #2508).

### Steps to reproduce the problem
Create a plugin that registers a pipeline-function, deploy this with the latest 2.1 preview (server:2.1.0-beta.3-1). 
The following exception will occur: java.lang.ClassNotFoundException: org.graylog.plugins.pipelineprocessor.ast.functions.AbstractFunction

I suppose adding a graylog-plugin.properties files containing the line isolated=false in both the the pipeline-plugin as well as the plugin implementing the custom pipeline-function would resolve the problem..

### Environment

* Graylog Version:2.1.0-beta.3-1
* Pipeline Processor plugin version:1.1.0-beta.3.
* Elasticsearch Version:
* MongoDB Version:
* Operating System: linux
* Browser version:

**Comment by kroepke** [comment]
We will enable this for the next release (beta.4 is already being built as I write this)
