### ISSUE TITLE
No eror shown in rule ediior, if wrong timezone passed to parse_date()

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog-plugin-pipeline-processor#84]
### Problem description
I've created rule:
![image](https://cloud.githubusercontent.com/assets/17475270/17671682/f5b67806-6320-11e6-9e2a-7d9491fc62a5.png)

No errors displayed, but on pressing save error shown at the bottom of page:
![image](https://cloud.githubusercontent.com/assets/17475270/17671727/2a36c842-6321-11e6-9253-cfd365f2f189.png)

And REST response contains correct error:
`{"type":"ApiError","message":"The datetime zone id '123' is not recognised"}`

### Environment
* Graylog Version: 2.1.0-beta3
* Pipeline Processor plugin version: 1.1.0-beta.3

**Comment by kroepke** [comment]
Yes, there's a missing parse error handler for constant arguments at https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/5cd12d67fff260485f25083ef39d03765ff1ff03/src/main/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParser.java#L360-L360

**Comment by kroepke** [comment]
<img width="915" alt="tz" src="https://cloud.githubusercontent.com/assets/52014/17810207/12821dde-661c-11e6-95c3-e4ae33cb87c9.png">

**Comment by kroepke** [comment]
I've added a proper error message for this class of errors and improved the timezone handling a bit (by allowing arbitrary casing for the timezone name, had to be uppercase before).
