### ISSUE TITLE
Implement non-equality comparison of DateTime values

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog-plugin-pipeline-processor#86]
### Problem description
I want to drop old messages in rule.
So I need to compare timestamp of message with current time

### Environment
* Graylog Version: 2.1.0-beta3
* Pipeline Processor plugin version: 1.1.0-beta3

**Comment by edmundoa** [comment]
Hi,

You can use the [`now()`](http://docs.graylog.org/en/2.0/pages/pipelines/functions.html#now) function to get the current time. Here is an example of how to use it: https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/68dabe5bd39697f94b9604e47de5b59170f1f308/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/dates.txt

**Comment by hc4** [comment]
And again I didn't find needed function :)
Maybe create some reflection to search for available functions, likie it done for REST API?

**Comment by hc4** [comment]
And still unable to compare dates, because timestamp field is Object
![image](https://cloud.githubusercontent.com/assets/17475270/17694546/072ba6f6-63ad-11e6-9b97-2bdc4ab9b3e4.png)

**Comment by edmundoa** [comment]
I think you need to parse the date time in the timestamp field of your message, probably with something like:
```
let timestamp = parse_date($message.timestamp, "yyyy-MM-dd'T'HH:mm:ssZZ");
```

And then you could subtract the two months from the `timestamp` variable, which should be a `DateTime` instance at that point.

**Comment by hc4** [comment]
but field timestamp already should be DateTime?
It is strange to convert it to string and then parse again...

**Comment by hc4** [comment]
plus/minus-methods not avaialble for DateTime:
![image](https://cloud.githubusercontent.com/assets/17475270/17694816/5e74da3a-63ae-11e6-9fb4-c72a9970114d.png)

**Comment by edmundoa** [comment]
I'm not sure if we are implicitly converting all message timestamps into `DateTime` objects, to be honest. It is also not possible to call `DateTime`'s methods, only access its properties. I would say we are still missing some math functions for dates.

**Comment by kroepke** [comment]
This seems to be a bug. Special handling for `DateTime` is implemented in `==` and `!=` but not in the other comparison operators.

After that fix it should work as expected.

**Comment by kroepke** [comment]
Tentative for 1.1.0, not sure if we can get to it.
